parameters: {}
environment: {
  ENV: production,
  LOG_DESTINATIONS: ${LOG_DESTINATIONS}

}
packages:
    - name: v1
      shared: false
      environment: {
        DATABASE_URL: "${DATABASE_URL}",
        JWT_SECRET_KEY: ${JWT_SECRET_KEY},
        OPENAI_API_KEY: "${OPENAI_API_KEY}",
        STRIPE_SECRET_KEY: "${STRIPE_SECRET_KEY}",
        AIAGENT_PRODUCT_ID: ${AIAGENT_PRODUCT_ID},
        ACTIVE_STATUS: ${ACTIVE_STATUS},
        CLOUDINARY_CLOUD_NAME: ${CLOUDINARY_CLOUD_NAME},
        CLOUDINARY_API_KEY: "${CLOUDINARY_API_KEY}",
        CLOUDINARY_API_SECRET: ${CLOUDINARY_API_SECRET}
      }
      parameters: {}
      annotations: {}
      functions:
        - name: explore_groups
          binary: false
          main: ""
          runtime: python:default
          web: true
          parameters: {}
          environment: {}
          annotations: {}
          limits: {}
        - name: external_accounts
          binary: false
          main: ""
          runtime: python:default
          web: true
          parameters: {}
          environment: {
            GOOGLE_APPLICATION_CREDENTIALS_JSON: "${GOOGLE_APPLICATION_CREDENTIALS_JSON}"          }
          annotations: {}
          limits: {}
        - name: objects
          binary: false
          main: ""
          runtime: python:default
          web: true
          parameters: {}
          environment: {}
          annotations: {}
          limits: {}
        - name: compositions
          binary: false
          main: ""
          runtime: python:default
          web: true
          parameters: {}
          environment: {}
          annotations: {}
          limits: {}
        - name: solution_groups
          binary: false
          main: ""
          runtime: python:default
          web: true
          parameters: {}
          environment: {}
          annotations: {}
          limits: {}
        - name: solution_templates
          binary: false
          main: ""
          runtime: python:default
          web: true
          parameters: {}
          environment: {}
          annotations: {}
          limits: {}    
        - name: workflow_templates
          binary: false
          main: ""
          runtime: python:default
          web: true
          parameters: {}
          environment: {}
          annotations: {}
          limits: {}
